# Generated by Django 4.0 on 2022-11-04 07:25

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BukuTamu',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nama', models.TextField(max_length=50)),
                ('perusahaan', models.TextField(max_length=100)),
                ('jumlah_tamu', models.IntegerField()),
                ('tujuan', models.TextField(max_length=100)),
                ('keperluan', models.TextField(max_length=200)),
                ('create_date', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'bukutamu',
                'verbose_name_plural': 'bukutamus',
            },
        ),
    ]
