# Generated by Django 4.0 on 2023-05-22 07:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('guest_book', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='bukutamu',
            name='tgl_akhir',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='bukutamu',
            name='tgl_awal',
            field=models.DateField(blank=True, null=True),
        ),
    ]
